#!/usr/bin/env bash
# Standing objective-strength tracker for a training run. The in-run vitals
# (draw_frac, attacks) are behavioral only; this measures actual strength:
# every ckpt_N.safetensors not yet in $RUN/strength.jsonl gets
#   (a) win share vs the fixed HeuristicBot baseline (2 seeds), and
#   (b) direct net-vs-net win share vs the run's anchor checkpoint —
#       the only signal that shows self-play improvement once the scripted
#       baseline saturates.
# Appends one JSON line per checkpoint and regenerates $RUN/STRENGTH.md
# (the at-a-glance table). Evals run in a separate process by design
# (see eval_ckpt.py); a failed eval (e.g. a Metal fault under GPU
# contention) is skipped and retried on the next pass.
#
# Usage: nohup ./watch_strength.sh [run_dir] [anchor_ckpt] &
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

RUN_GLOB="${1:-runs/marathon_r*}"
ANCHOR="${2:-runs/marathon1c/ckpt_100.safetensors}"
SLEEP="${SLEEP:-900}"
GAMES="${GAMES:-200}"

write_md() {
  {
    echo "# $RUN — objective strength (auto-generated by watch_strength.sh)"
    echo
    echo "ws = win share, hero rotated, 0.5 = parity. ws_heur: vs HeuristicBot"
    echo "(fixed scripted baseline, 2 seeds). ws_anchor: net-vs-net vs"
    echo "$ANCHOR (EMA) — the self-play improvement signal."
    echo
    echo "| ckpt | ws_heur | ema_ws_heur | ws_anchor | ema_ws_anchor | ws_doi_l5 | measured |"
    echo "|---|---|---|---|---|---|---|"
    jq -r '[.ckpt, (.ws_heur*1000|round/1000), (.ema_ws_heur*1000|round/1000),
            (.ws_ckpt*1000|round/1000), (.ema_ws_ckpt*1000|round/1000),
            (if .ws_doi then (.ws_doi*1000|round/1000) else "-" end), .ts]
           | "| \(.[0]) | \(.[1]) | \(.[2]) | \(.[3]) | \(.[4]) | \(.[5]) | \(.[6]) |"' "$OUT" \
      | sort -t_ -k2 -n
  } >"$MD"
}

while true; do
  for RUN in $RUN_GLOB; do
    [[ -d "$RUN" ]] || continue
    OUT="$RUN/strength.jsonl"
    MD="$RUN/STRENGTH.md"
  for ck in $(ls "$RUN"/ckpt_*.safetensors 2>/dev/null | sort -t_ -k2 -n); do
    name=$(basename "$ck" .safetensors)
    grep -q "\"ckpt\": \"$name\"" "$OUT" 2>/dev/null && continue
    heur=$(.venv/bin/python -m stratego_trainer.eval_ckpt --ckpt "$ck" \
      --opponent heuristic --seeds 0,1 --games "$GAMES" 2>/dev/null | tail -1) || continue
    anchor=$(.venv/bin/python -m stratego_trainer.eval_ckpt --ckpt "$ck" \
      --opponent "$ANCHOR" --seed 0 --games "$GAMES" 2>/dev/null | tail -1) || continue
    doi=$(.venv/bin/python calibration/eval_vs_doi.py --ckpt "$ck" \
      --games 20 --doi-level 5 2>/dev/null | tail -1) || doi='{}'
    [[ -z "$heur" || -z "$anchor" ]] && continue
    ts=$(date -u +%Y-%m-%dT%H:%M:%SZ)
    python3 - "$name" "$heur" "$anchor" "$doi" "$ts" <<'PY' >>"$OUT" || continue
import json, sys
name, heur, anchor, doi, ts = sys.argv[1:6]
d = {"ckpt": name}
d.update(json.loads(heur))
d.update(json.loads(anchor))
try:
    d.update(json.loads(doi))
except json.JSONDecodeError:
    pass
d["ts"] = ts
print(json.dumps(d))
PY
    write_md
  done
  done
  sleep "$SLEEP"
done
